name 'debug_attributes'
maintainer 'Richard Nixon'
maintainer_email 'richard.nixon@btinternet.com'
license 'All Rights Reserved'
description 'Lets you see where attributes are getting set'
version '0.1.0'
chef_version '>= 14.0'

issues_url 'https://github.com/trickyearlobe/debug_attributes/issues'
source_url 'https://github.com/trickyearlobe/debug_attributes'
